### ISSUE TITLE
Add gopherjs to travis.yml

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#249]
It'd be nice if we tested the build integrity of `engo` w.r.t. gopherjs as well. 

Should be done after #247, though. 

Something I found on the web:
```
language: go
go:
  - 1.5
addons:
  apt:
    packages:
      - nodejs
install:
  - go get -u github.com/gopherjs/gopherjs
script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - gopherjs test
```

I can imagine we also have to use that `script` tag to define it. Not sure if we have to write some weird script to find all `main` files, though. (Travis now does that for us, using just Go)
